### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by enoqueJonas** [enoqueJonas/tutoring-app-backend#11]
# Final group capstone: set up your Kanban board
- There are 4 people in our group
- [Project Link](https://github.com/users/enoqueJonas/projects/3/views/1)

<img width="1440" alt="Screen Shot 2023-06-07 at 19 37 09" src="https://github.com/enoqueJonas/tutoring-app-backend/assets/76396858/b5aa9a67-4a61-42d7-9e25-a37a471ef039">

<img width="1440" alt="Screen Shot 2023-06-07 at 19 37 26" src="https://github.com/enoqueJonas/tutoring-app-backend/assets/76396858/c519f834-69f3-4041-b238-af54aa372688">

## Students
- Student A [Jorge](@jorgeabrahan)
- Student B [Anas](@anas599)
- Student C [Enoque](@enoqueJonas)
- Student D [Uthman]()

**Comment by Meltrust** [comment]
Hi student,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that I can't access because the link is private.

![image](https://github.com/enoqueJonas/tutoring-app-backend/assets/57421823/dcd71f03-c695-48f2-9f31-d1c1fbfa5f24)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
